### ISSUE TITLE
Support custom retry widgets.

### ISSUE THREAD

**Issue by CarpOrange** [Mahmoud-Saeed-Mahmoud/loading_state_handler#2]
I would like to customize the error state text, but the default widget's error message is hardcoded. The current implementation does not meet my needs.

Current Issue:
Hardcoded Error Text:

The text displayed for error state is hardcoded in the widget, and I would like to customize it.
![image](https://github.com/user-attachments/assets/577a0cd1-10e9-4205-bcc9-fcb598b57892)
<img width="624" alt="image" src="https://github.com/user-attachments/assets/cf472d0a-2063-4e96-9e78-2431760766d2" />

Default Error Builder Limitation:

I found the defaultErrorBuilder feature, but it still does not fulfill my requirements. Specifically, I cannot specify my retry button’s onPressed, because the defaultErrorBuilder does not pass widget.onRetry and _remainingCooldown.
![image](https://github.com/user-attachments/assets/891733f9-8a8d-409e-99fe-97a27639828f)

Suggested Improvements:
Allow customization of the error text, making it possible for developers to pass their own error messages.
Or pass the onRetry callback and _remainingCooldown to the defaultErrorBuilder so that the retry button can be customized, including the button's text.

**Comment by Mahmoud-Saeed-Mahmoud** [comment]
@CarpOrange please upgrade to v1.3.0 and you can set a retry button text and a retry message with style and the retry button style as well.
hence the `defaultErrorBuilder` will provide the entire retryWidget, retryCooldown, and the onRetry you can just use the retryWidget it will apply everything automatically or you can use retryCooldown and onRetry for customization.

**Comment by CarpOrange** [comment]
@Mahmoud-Saeed-Mahmoud Thank you for the quick update! I tried version 1.3.2, and it perfectly solved my issue.
